/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.todo.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TodoEntry service. Represents a row in the &quot;TDL_TodoEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.todo.model.impl.TodoEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.todo.model.impl.TodoEntryImpl</code>.
 * </p>
 *
 * @author Ryan Park
 * @see TodoEntry
 * @generated
 */
@ProviderType
public interface TodoEntryModel
	extends BaseModel<TodoEntry>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todo entry model instance should use the {@link TodoEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this todo entry.
	 *
	 * @return the primary key of this todo entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todo entry.
	 *
	 * @param primaryKey the primary key of this todo entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the todo entry ID of this todo entry.
	 *
	 * @return the todo entry ID of this todo entry
	 */
	public long getTodoEntryId();

	/**
	 * Sets the todo entry ID of this todo entry.
	 *
	 * @param todoEntryId the todo entry ID of this todo entry
	 */
	public void setTodoEntryId(long todoEntryId);

	/**
	 * Returns the group ID of this todo entry.
	 *
	 * @return the group ID of this todo entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this todo entry.
	 *
	 * @param groupId the group ID of this todo entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this todo entry.
	 *
	 * @return the company ID of this todo entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this todo entry.
	 *
	 * @param companyId the company ID of this todo entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this todo entry.
	 *
	 * @return the user ID of this todo entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this todo entry.
	 *
	 * @param userId the user ID of this todo entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this todo entry.
	 *
	 * @return the user uuid of this todo entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this todo entry.
	 *
	 * @param userUuid the user uuid of this todo entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this todo entry.
	 *
	 * @return the user name of this todo entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this todo entry.
	 *
	 * @param userName the user name of this todo entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this todo entry.
	 *
	 * @return the create date of this todo entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this todo entry.
	 *
	 * @param createDate the create date of this todo entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this todo entry.
	 *
	 * @return the modified date of this todo entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this todo entry.
	 *
	 * @param modifiedDate the modified date of this todo entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this todo entry.
	 *
	 * @return the title of this todo entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this todo entry.
	 *
	 * @param title the title of this todo entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the priority of this todo entry.
	 *
	 * @return the priority of this todo entry
	 */
	public int getPriority();

	/**
	 * Sets the priority of this todo entry.
	 *
	 * @param priority the priority of this todo entry
	 */
	public void setPriority(int priority);

	/**
	 * Returns the assignee user ID of this todo entry.
	 *
	 * @return the assignee user ID of this todo entry
	 */
	public long getAssigneeUserId();

	/**
	 * Sets the assignee user ID of this todo entry.
	 *
	 * @param assigneeUserId the assignee user ID of this todo entry
	 */
	public void setAssigneeUserId(long assigneeUserId);

	/**
	 * Returns the assignee user uuid of this todo entry.
	 *
	 * @return the assignee user uuid of this todo entry
	 */
	public String getAssigneeUserUuid();

	/**
	 * Sets the assignee user uuid of this todo entry.
	 *
	 * @param assigneeUserUuid the assignee user uuid of this todo entry
	 */
	public void setAssigneeUserUuid(String assigneeUserUuid);

	/**
	 * Returns the resolver user ID of this todo entry.
	 *
	 * @return the resolver user ID of this todo entry
	 */
	public long getResolverUserId();

	/**
	 * Sets the resolver user ID of this todo entry.
	 *
	 * @param resolverUserId the resolver user ID of this todo entry
	 */
	public void setResolverUserId(long resolverUserId);

	/**
	 * Returns the resolver user uuid of this todo entry.
	 *
	 * @return the resolver user uuid of this todo entry
	 */
	public String getResolverUserUuid();

	/**
	 * Sets the resolver user uuid of this todo entry.
	 *
	 * @param resolverUserUuid the resolver user uuid of this todo entry
	 */
	public void setResolverUserUuid(String resolverUserUuid);

	/**
	 * Returns the due date of this todo entry.
	 *
	 * @return the due date of this todo entry
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this todo entry.
	 *
	 * @param dueDate the due date of this todo entry
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the finish date of this todo entry.
	 *
	 * @return the finish date of this todo entry
	 */
	public Date getFinishDate();

	/**
	 * Sets the finish date of this todo entry.
	 *
	 * @param finishDate the finish date of this todo entry
	 */
	public void setFinishDate(Date finishDate);

	/**
	 * Returns the status of this todo entry.
	 *
	 * @return the status of this todo entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this todo entry.
	 *
	 * @param status the status of this todo entry
	 */
	public void setStatus(int status);

}