/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.todo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.todo.model.TodoEntry;
import com.liferay.todo.model.TodoEntryModel;
import com.liferay.todo.model.TodoEntrySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TodoEntry service. Represents a row in the &quot;TDL_TodoEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TodoEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TodoEntryImpl}.
 * </p>
 *
 * @author Ryan Park
 * @see TodoEntryImpl
 * @generated
 */
@JSON(strict = true)
public class TodoEntryModelImpl
	extends BaseModelImpl<TodoEntry> implements TodoEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a todo entry model instance should use the <code>TodoEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "TDL_TodoEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"todoEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"priority", Types.INTEGER}, {"assigneeUserId", Types.BIGINT},
		{"resolverUserId", Types.BIGINT}, {"dueDate", Types.TIMESTAMP},
		{"finishDate", Types.TIMESTAMP}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("todoEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("assigneeUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resolverUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("finishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table TDL_TodoEntry (todoEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,priority INTEGER,assigneeUserId LONG,resolverUserId LONG,dueDate DATE null,finishDate DATE null,status INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table TDL_TodoEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY todoEntry.priority ASC, todoEntry.dueDate ASC, todoEntry.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY TDL_TodoEntry.priority ASC, TDL_TodoEntry.dueDate ASC, TDL_TodoEntry.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long ASSIGNEEUSERID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long RESOLVERUSERID_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long USERID_COLUMN_BITMASK = 16L;

	public static final long PRIORITY_COLUMN_BITMASK = 32L;

	public static final long DUEDATE_COLUMN_BITMASK = 64L;

	public static final long CREATEDATE_COLUMN_BITMASK = 128L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TodoEntry toModel(TodoEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TodoEntry model = new TodoEntryImpl();

		model.setTodoEntryId(soapModel.getTodoEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setTitle(soapModel.getTitle());
		model.setPriority(soapModel.getPriority());
		model.setAssigneeUserId(soapModel.getAssigneeUserId());
		model.setResolverUserId(soapModel.getResolverUserId());
		model.setDueDate(soapModel.getDueDate());
		model.setFinishDate(soapModel.getFinishDate());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TodoEntry> toModels(TodoEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TodoEntry> models = new ArrayList<TodoEntry>(soapModels.length);

		for (TodoEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public TodoEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _todoEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTodoEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _todoEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TodoEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TodoEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TodoEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TodoEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TodoEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TodoEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TodoEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TodoEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TodoEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TodoEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TodoEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, TodoEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			TodoEntry.class.getClassLoader(), TodoEntry.class,
			ModelWrapper.class);

		try {
			Constructor<TodoEntry> constructor =
				(Constructor<TodoEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<TodoEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TodoEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TodoEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<TodoEntry, Object>>();
		Map<String, BiConsumer<TodoEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<TodoEntry, ?>>();

		attributeGetterFunctions.put("todoEntryId", TodoEntry::getTodoEntryId);
		attributeSetterBiConsumers.put(
			"todoEntryId",
			(BiConsumer<TodoEntry, Long>)TodoEntry::setTodoEntryId);
		attributeGetterFunctions.put("groupId", TodoEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<TodoEntry, Long>)TodoEntry::setGroupId);
		attributeGetterFunctions.put("companyId", TodoEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<TodoEntry, Long>)TodoEntry::setCompanyId);
		attributeGetterFunctions.put("userId", TodoEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<TodoEntry, Long>)TodoEntry::setUserId);
		attributeGetterFunctions.put("userName", TodoEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<TodoEntry, String>)TodoEntry::setUserName);
		attributeGetterFunctions.put("createDate", TodoEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TodoEntry, Date>)TodoEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TodoEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TodoEntry, Date>)TodoEntry::setModifiedDate);
		attributeGetterFunctions.put("title", TodoEntry::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<TodoEntry, String>)TodoEntry::setTitle);
		attributeGetterFunctions.put("priority", TodoEntry::getPriority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<TodoEntry, Integer>)TodoEntry::setPriority);
		attributeGetterFunctions.put(
			"assigneeUserId", TodoEntry::getAssigneeUserId);
		attributeSetterBiConsumers.put(
			"assigneeUserId",
			(BiConsumer<TodoEntry, Long>)TodoEntry::setAssigneeUserId);
		attributeGetterFunctions.put(
			"resolverUserId", TodoEntry::getResolverUserId);
		attributeSetterBiConsumers.put(
			"resolverUserId",
			(BiConsumer<TodoEntry, Long>)TodoEntry::setResolverUserId);
		attributeGetterFunctions.put("dueDate", TodoEntry::getDueDate);
		attributeSetterBiConsumers.put(
			"dueDate", (BiConsumer<TodoEntry, Date>)TodoEntry::setDueDate);
		attributeGetterFunctions.put("finishDate", TodoEntry::getFinishDate);
		attributeSetterBiConsumers.put(
			"finishDate",
			(BiConsumer<TodoEntry, Date>)TodoEntry::setFinishDate);
		attributeGetterFunctions.put("status", TodoEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<TodoEntry, Integer>)TodoEntry::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getTodoEntryId() {
		return _todoEntryId;
	}

	@Override
	public void setTodoEntryId(long todoEntryId) {
		_todoEntryId = todoEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		_columnBitmask = -1L;

		_priority = priority;
	}

	@JSON
	@Override
	public long getAssigneeUserId() {
		return _assigneeUserId;
	}

	@Override
	public void setAssigneeUserId(long assigneeUserId) {
		_columnBitmask |= ASSIGNEEUSERID_COLUMN_BITMASK;

		if (!_setOriginalAssigneeUserId) {
			_setOriginalAssigneeUserId = true;

			_originalAssigneeUserId = _assigneeUserId;
		}

		_assigneeUserId = assigneeUserId;
	}

	@Override
	public String getAssigneeUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAssigneeUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setAssigneeUserUuid(String assigneeUserUuid) {
	}

	public long getOriginalAssigneeUserId() {
		return _originalAssigneeUserId;
	}

	@JSON
	@Override
	public long getResolverUserId() {
		return _resolverUserId;
	}

	@Override
	public void setResolverUserId(long resolverUserId) {
		_columnBitmask |= RESOLVERUSERID_COLUMN_BITMASK;

		if (!_setOriginalResolverUserId) {
			_setOriginalResolverUserId = true;

			_originalResolverUserId = _resolverUserId;
		}

		_resolverUserId = resolverUserId;
	}

	@Override
	public String getResolverUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getResolverUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setResolverUserUuid(String resolverUserUuid) {
	}

	public long getOriginalResolverUserId() {
		return _originalResolverUserId;
	}

	@JSON
	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		_columnBitmask = -1L;

		_dueDate = dueDate;
	}

	@JSON
	@Override
	public Date getFinishDate() {
		return _finishDate;
	}

	@Override
	public void setFinishDate(Date finishDate) {
		_finishDate = finishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TodoEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TodoEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TodoEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TodoEntryImpl todoEntryImpl = new TodoEntryImpl();

		todoEntryImpl.setTodoEntryId(getTodoEntryId());
		todoEntryImpl.setGroupId(getGroupId());
		todoEntryImpl.setCompanyId(getCompanyId());
		todoEntryImpl.setUserId(getUserId());
		todoEntryImpl.setUserName(getUserName());
		todoEntryImpl.setCreateDate(getCreateDate());
		todoEntryImpl.setModifiedDate(getModifiedDate());
		todoEntryImpl.setTitle(getTitle());
		todoEntryImpl.setPriority(getPriority());
		todoEntryImpl.setAssigneeUserId(getAssigneeUserId());
		todoEntryImpl.setResolverUserId(getResolverUserId());
		todoEntryImpl.setDueDate(getDueDate());
		todoEntryImpl.setFinishDate(getFinishDate());
		todoEntryImpl.setStatus(getStatus());

		todoEntryImpl.resetOriginalValues();

		return todoEntryImpl;
	}

	@Override
	public int compareTo(TodoEntry todoEntry) {
		int value = 0;

		if (getPriority() < todoEntry.getPriority()) {
			value = -1;
		}
		else if (getPriority() > todoEntry.getPriority()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getDueDate(), todoEntry.getDueDate());

		if (value != 0) {
			return value;
		}

		value = DateUtil.compareTo(getCreateDate(), todoEntry.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TodoEntry)) {
			return false;
		}

		TodoEntry todoEntry = (TodoEntry)obj;

		long primaryKey = todoEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TodoEntryModelImpl todoEntryModelImpl = this;

		todoEntryModelImpl._originalGroupId = todoEntryModelImpl._groupId;

		todoEntryModelImpl._setOriginalGroupId = false;

		todoEntryModelImpl._originalUserId = todoEntryModelImpl._userId;

		todoEntryModelImpl._setOriginalUserId = false;

		todoEntryModelImpl._setModifiedDate = false;

		todoEntryModelImpl._originalAssigneeUserId =
			todoEntryModelImpl._assigneeUserId;

		todoEntryModelImpl._setOriginalAssigneeUserId = false;

		todoEntryModelImpl._originalResolverUserId =
			todoEntryModelImpl._resolverUserId;

		todoEntryModelImpl._setOriginalResolverUserId = false;

		todoEntryModelImpl._originalStatus = todoEntryModelImpl._status;

		todoEntryModelImpl._setOriginalStatus = false;

		todoEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TodoEntry> toCacheModel() {
		TodoEntryCacheModel todoEntryCacheModel = new TodoEntryCacheModel();

		todoEntryCacheModel.todoEntryId = getTodoEntryId();

		todoEntryCacheModel.groupId = getGroupId();

		todoEntryCacheModel.companyId = getCompanyId();

		todoEntryCacheModel.userId = getUserId();

		todoEntryCacheModel.userName = getUserName();

		String userName = todoEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			todoEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			todoEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			todoEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			todoEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			todoEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		todoEntryCacheModel.title = getTitle();

		String title = todoEntryCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			todoEntryCacheModel.title = null;
		}

		todoEntryCacheModel.priority = getPriority();

		todoEntryCacheModel.assigneeUserId = getAssigneeUserId();

		todoEntryCacheModel.resolverUserId = getResolverUserId();

		Date dueDate = getDueDate();

		if (dueDate != null) {
			todoEntryCacheModel.dueDate = dueDate.getTime();
		}
		else {
			todoEntryCacheModel.dueDate = Long.MIN_VALUE;
		}

		Date finishDate = getFinishDate();

		if (finishDate != null) {
			todoEntryCacheModel.finishDate = finishDate.getTime();
		}
		else {
			todoEntryCacheModel.finishDate = Long.MIN_VALUE;
		}

		todoEntryCacheModel.status = getStatus();

		return todoEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TodoEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TodoEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TodoEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TodoEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TodoEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TodoEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TodoEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TodoEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TodoEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _todoEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _title;
	private int _priority;
	private long _assigneeUserId;
	private long _originalAssigneeUserId;
	private boolean _setOriginalAssigneeUserId;
	private long _resolverUserId;
	private long _originalResolverUserId;
	private boolean _setOriginalResolverUserId;
	private Date _dueDate;
	private Date _finishDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _columnBitmask;
	private TodoEntry _escapedModel;

}